# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html

run:
  prefix: "adm2324"
  name: [year_hot] # or multiple: [year_cold, year_hot, ...]
  scenarios:
    enable: true
    file: config/scenarios.template.yaml
  use_shadow_directory: true

scenario:
  clusters: [adm]

countries: ['CH', "DE"]

# change it to correct weather year
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: left

electricity:
  renewable_carriers: [solar, solar-hsat, onwind, alpine-solar, hydro]
  extendable_carriers: # don't extend hydro and PHS
    Generator: [solar, solar-hsat, onwind, alpine-solar]
    StorageUnit: [] 

#review this again
#insert my desired cutouts
atlite:
  nprocesses: 8
  show_progress: true
  cutouts: # load cutouts from HDD into cutouts folder here
    cold_year:
      x : [5.95, 10.47]
      y : [45.82, 47.81]
      time : ["1941-10-01", "1942-03-31"]
      module: era5
    
    high_albedo_year:
      x : [5.95, 10.47]
      y : [45.82, 47.81]
      time : ["1962-10-01", "1963-03-31"]
      module: era5

    europe_2023_2024: # name of warm year cutout under data/cutout/archive/v1.0
      x : [-12, 42]
      y : [33, 72]
      time : ["2023-10-01", "2024-03-31"]
      module: era5

    low_albedo_year:
      x : [5.95, 10.47]
      y : [45.82, 47.81]
      time : ["2006-10-01", "2007-03-31"]
      module: era5

    medium_year:
      x : [5.95, 10.47]
      y : [45.82, 47.81]
      time : ["1981-10-01", "1982-03-31"]
      module: era5

# I just left out offwind, is that okay?
# do I have to download wind data in the cutouts for onwind?
# same for hydro stuff?

renewable:
  onwind:
    cutout: default
  solar:
    cutout: default
  solar-hsat:
    cutout: default
  hydro:
    cutout: default


  alpine-solar:
    cutout: default
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 65.0 # only in the presence of snow, without snow its 52.0 Degrees
        azimuth: 180.0
      tracking:
    resource_classes: 1
    capacity_per_sqkm: 5.1 # change, find reference for this
    correction_factor: 1.0
    corine:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 26
    - 31
    - 32
    luisa: false
    natura: true
    excluder_resolution: 100
    clip_p_max_pu: 0.01

# added this, because otherwise it didn't find data for 2024
# I guess it can only calculate / look at 1 year?
load:
  fixed_year: 2023


# here starts the sector-coupled part
pypsa_eur:
  Bus: [AC]
  Link: [DC] # energz conversion, DC powerline is transporting electricity
  Line: [AC] # without conversion
  Generator: [solar, solar-hsat, onwind, ror, alpine-solar, ror] # carrying through to SC model 
  StorageUnit: [hydro, PHS] 
  Store: []

solar_thermal:
  cutout: default

clustering:
  mode: administrative
  administrative:
    level: 0 # other countries are only 1 cluster each
    CH: 3 # only Switzerland is set to Nuts3
  temporal:
    resolution_sector: 3H # (limit of diurnal storage (Mai, 2022) is 24H; 3H justified in Gotske, 2024)

sector:
  transport: true

  heating: true
  district_heating:
    potential: 0.6
  
  biomass: true

  industry: false # set to true later
  ammonia: false
  SMR: false # green H2 only
  SMR_cc: false # NB. industrial/fertiliser demand for ammonia counted using H2 and elec. demand
  methanation: false

  fossil_fuels: false # fully renewable, this flag = true implies there's a way to spawn in CH4/oil/coal into the network
  gas_network: false # true # adds: link 'gas pipeline', link 'gas pipeline new', minimum capacity on store 'gas'
  
  dac: true # might need to catch excess carbon emissions from somewhere
  co2_network: false
  co2_spatial: false # what exactly is this?

  H2_network: false
  H2_retrofit: false # true
  hydrogen_fuel_cell: true
  hydrogen_turbine: true

  electricity_transmission_grid: true
  electricity_distribution_grid: true # this sets solar cost to cost of utility (freifläche) and not 50-50 utility-rooftop 



### additional? ###
### all false from here ###

  shipping: false
  aviation: false
  agriculture: false

  bev_dsm: false
  v2g: false

  tes: false
  boilers: false
  resistive_heaters: false
  biomass_boiler: false

  chp:
    enable: false

  solar_thermal: false

  heat_vent:
    urban central: false
    urban decentral: false
    rural: false

  regional_oil_demand: false

  regional_co2_sequestration_potential:
    enable: false

  hydrogen_underground_storage: false

  methanol:
    methanol_to_power:
      ocgt: false
    biomass_to_methanol: false

  electricity_grid_connection: true

  gas_distribution_grid: false

  biomass_spatial: false

  biogas_upgrading: false
  
  conventional_generation: {}
    #OCGT: gas
    #CCGT: gas

  biomass_to_liquid: false
  electrobiofuels: false