
baseline: {}

medium_alpine:
  electricity:
    renewable_carriers: [alpine-solar, solar, solar-hsat, onwind, hydro]
    extendable_carriers:
      Generator: [alpine-solar, solar, solar-hsat, onwind]
  pypsa_eur:
    Generator: [alpine-solar, solar, solar-hsat, onwind, ror]

medium_alpine_offwind:
  electricity:
    renewable_carriers: [alpine-solar, solar, solar-hsat, onwind, hydro, offwind-ac, offwind-dc]
    extendable_carriers:
      Generator: [alpine-solar, solar, solar-hsat, onwind, offwind-ac, offwind-dc] # 
  pypsa_eur:
    Generator: [alpine-solar, solar, solar-hsat, onwind, ror, offwind-ac, offwind-dc]

medium_alpine_industry:
  electricity:
    renewable_carriers: [alpine-solar, solar, solar-hsat, onwind, hydro]
    extendable_carriers:
      Generator: [alpine-solar, solar, solar-hsat, onwind]
  pypsa_eur:
    Generator: [alpine-solar, solar, solar-hsat, onwind, ror]
  sector:
    industry: true

medium_alpine_industry_offwind:
  electricity:
    renewable_carriers: [alpine-solar, solar, solar-hsat, onwind, hydro, offwind-ac, offwind-dc]
    extendable_carriers:
      Generator: [alpine-solar, solar, solar-hsat, onwind, offwind-ac, offwind-dc]
  pypsa_eur:
    Generator: [alpine-solar, solar, solar-hsat, onwind, ror, offwind-ac, offwind-dc]
  sector:
    industry: true